### ISSUE TITLE
Remove Drupal 'nodequeue' module and 'islandora_google_scholar' references

### ISSUE THREAD

**Issue by McFateM** [Islandora-Collaboration-Group/ISLE-Drupal-Build-Tools#20]
The Drupal 'nodequeue' module is no longer supported, and attempting to include it kills the installer script.  I don't believe it is necessary in any Islandora stack so it should be removed entirely.

The 'islandora_google_scholar' module has been refactored to 'islandora_scholar'.  All references to 'islandora_google_scholar' should also be removed to eliminate inconsequential, but annoying, warnings and errors.

**Comment by bseeger** [comment]
Resolved by https://github.com/Islandora-Collaboration-Group/ISLE-Drupal-Build-Tools/pull/21
